agent:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      splunk_hec:
        endpoint: https://ingest.$REALM.signalfx.com/v1/log
        token: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}
      logging/info:
        loglevel: info
    service:
      pipelines:
        logs/profiling:
          exporters:
            - logging/info
            - splunk_hec
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
splunkObservability:
  accessToken: $ACCESS_TOKEN
  realm: $REALM