baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Realtime Data Enrichment Workshop'
theme:
  - docsy
enableGitInfo: true
taxonomies:
  tag: tags
  category: categories
contentDir: content
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
ui:
  breadcrumb_disable: false
  footer_about_disable: false
  navbar_logo: true
  navbar_translucent_over_cover_disable: false
  sidebar_menu_compact: false
  sidebar_search_disable: false
  sidebar_menu_foldable: false
  readingtime:
    enable: true

links:
  developer:
    - name: "GitHub"
      url: "https://github.com/signalfx/"
      icon: "fab fa-github"
  user:
    - name: Twitter
      url: 'https://twitter.com/splunk'
      icon: fab fa-twitter
      desc: Follow us on Twitter to get the latest news!

permalinks:
  blog: '/:section/:year/:month/:day/:slug/'

imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    #    - print
    - RSS