apiVersion: apps/v1
kind: Deployment
metadata:
  name: userlookup
  labels:
    app: userlookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userlookup
  template:
    metadata:
      labels:
        app: userlookup
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: localhost:8000/userlookup-splkotel:0.01
        name: userlookup
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_SERVICE_NAME
            value: 'userlookup'
          - name: SPLUNK_METRICS_ENDPOINT
            value: "http://$(SPLUNK_OTEL_AGENT):9943"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(SPLUNK_OTEL_AGENT):4317"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: 'deployment.environment=rtapp-workshop-stevel'
        volumeMounts:
        - mountPath: /var/appdata
          name: appdata
      volumes:
      - name: appdata
        hostPath:
          path: /var/appdata