apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviewsproducer
  name: reviewsproducer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: reviewsproducer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reviewsproducer
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: localhost:8000/reviewsproducer-splkotel:0.01
        name: reviewsproducer
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: SPLUNK_METRICS_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):9943"
        - name: OTEL_SERVICE_NAME
          value: "reviewsproducer"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=rtapp-workshop-stevel"