apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-11-18T19:51:36Z"
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-14.4.1
  name: kafka
  namespace: default
  resourceVersion: "34870"
  uid: 3d0121a2-7c71-4f67-919e-60a5304699ce
spec:
  clusterIP: 10.43.174.193
  clusterIPs:
  - 10.43.174.193
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: kafka-client
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
