apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbdetails
  labels:
    app: mongodbdetails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbdetails
  template:
    metadata:
      labels:
        app: mongodbdetails
    spec:
      containers:
      - image: leungsteve/mongodbdetails-splkotel:1.1
        name: mongodbdetails
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: 'mongodbdetails'
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=lab'
