apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reviewsconsumer
  name: reviewsconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewsconsumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reviewsconsumer
    spec:
      containers:
        - image: leungsteve/reviewsconsumertomongo-splkotel:1.2
          name: reviewsconsumer
          resources: {}
          env:
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4317"
            - name: SPLUNK_METRICS_ENDPOINT
                value: "http://$(SPLUNK_OTEL_AGENT):9943"
            - name: OTEL_SERVICE_NAME
              value: "reviewsconsumer"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=lab"
