apiVersion: apps/v1
kind: Deployment
metadata:
  name: userlookup
  labels:
    app: userlookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userlookup
  template:
    metadata:
      labels:
        app: userlookup
    spec:
      containers:
      - image: leungsteve/userlookup-splkotel:1.0
        name: userlookup
        volumeMounts:
        - mountPath: /var/appdata
          name: appdata
        env:
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: 'userlookup'
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=lab'
      volumes:
      - name: appdata
        hostPath:
          path: /var/appdata
