apiVersion: apps/v1
kind: Deployment
metadata:
  name: businesslookup
  labels:
    app: businesslookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businesslookup
  template:
    metadata:
      labels:
        app: businesslookup
    spec:
      containers:
      - image: localhost:8000/businesslookup:0.01
        name: businesslookup
        volumeMounts:
        - mountPath: /var/appdata
          name: appdata
      volumes:
      - name: appdata
        hostPath:
          path: /var/appdata